// Generated by dts-bundle-generator v7.2.0

export interface Chart {
	circleRadius?: number;
	height?: number;
	width?: number;
	yValues?: number[];
}
declare const _default: ({ height: _height, width: _width, yValues, }: Chart) => JSX.Element;

export {
	_default as Chart,
};

export {};
