// Generated by dts-bundle-generator v7.2.0

export interface Chart {
  height?: number
  width?: number
  yValues?: number[]
}
declare const _default: import("react").MemoExoticComponent<
  ({ height, width, yValues }: Chart) => JSX.Element
>

export { _default as Chart }

export {}
